export enum GenreType {
  ACTION = 'ACTION',
  COMEDY = 'COMEDY',
  DRAMA = 'DRAMA',
  HORROR = 'HORROR',
  ROMANCE = 'ROMANCE',
  SCI_FI = 'SCI_FI',
  THRILLER = 'THRILLER',
  ANIMATION = 'ANIMATION',
  DOCUMENTARY = 'DOCUMENTARY',
  FANTASY = 'FANTASY',
}
